name: .NET Core CI

on:
  push:
    paths:
      - 'Application/**'
  pull_request:
    paths:
      - 'Application/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

        

    - name: Install dependencies
      run: dotnet restore ./src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Test
      run: dotnet test --no-restore --verbosity normal ./Application/tests/RazorPagesTestSample.Tests.csproj

    - name: Publish
      run: dotnet publish --configuration Release --no-build ./Application/src/RazorPagesTestSample.csproj