name: My Workflow

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "This is step 1"
            - name: Step 2
              run: echo "This is step 2"

    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              uses: actions/checkout@v2
            - name: Step 2
              uses: actions/setup-node@v2
            - name: Step 3
              uses: mscoutermarsh/cowsays-action@master
              with:
                text: "Hello from the cow!"
